app/urls.py
from django.urls import path
from .views import CarsList
app_name = "app"

urlpatterns = [
    path('', CarsList.as_view(), name='index'),
]

cars/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace="app")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)), 
    ] + urlpatterns

app/models.py
from django.db import models
from random import randint
from .colors import color_palette, rgb_to_web, nearest

# def random_color():
#     return randint(0,0xFFFFFF)


class Car(models.Model):
    vendor = models.CharField(max_length=40)
    model = models.CharField(max_length=40)
    year = models.SmallIntegerField()
    GEARBOX = (
        (0, "механика"),
        (1, "автомат"),
        (2, "робот"),
    )
    gearbox = models.SmallIntegerField(choices=GEARBOX, default=0)
    # color = models.PositiveIntegerField(default=random_color)
    color = models.CharField(max_length=20, default=tuple(color_palette)[0])

    def web_color(self):
        return rgb_to_web(self.color)

    # def nearest_color(self):
    #     return nearest(self.color)['color']['name']

app/views.py
from django.db.models import Q, Max, Min
from django.shortcuts import render
from django.views.generic import ListView
from .models import Car
from .colors import color_palette, rgb_to_web

# функция для отображения django_debug_toolbox у всех
def truefunc(*args, **kwargs): return True



class CarsList(ListView):
    # model = Car
    paginate_by=15

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # список кнопок управления паджинацией
        current_page = context['page_obj'].number
        total_pages = context['paginator'].num_pages
        nearest = 2

        context['page_list'] = [x for x in range(
            current_page-nearest, current_page+nearest+1) if x > 0 and x <= total_pages]

        # список производителей авто и разброс лет для работы с формами        
        # context['vendor_list'] = Car.objects.values_list('vendor', flat=True).distinct().order_by('vendor')
        
        # в таком виде работает в 3 раза быстрее:
        all_the_cars = Car.objects.values_list('vendor', 'year', named=True)
        context['vendor_list'] = sorted(set([x.vendor for x in all_the_cars]))

        # список доступных цветов для фильтрации списка
        context['colors'] = [{'name': key, 'web': rgb_to_web(value)} for key, value in color_palette.items()]
        return context

    def get_queryset(self, **kwargs):        
        output = Car.objects.all()

        query = Q()
        for key, value in dict(self.request.GET).items():
            if value != ['',] and key in vars(Car):
                if key == 'model':
                    query &= Q(**{f'{key}__contains': value[0]})
                elif key =='year':
                    query &=Q(**{f'{key}__in': [x for x in value[0].split(',') if str(x).isdigit()]})
                else:
                    query &= Q(**{f'{key}__in': value})

        return output.filter(query).order_by('id')

        # if all([
        #     'vendor' in self.request.GET, 
        #     'model' in self.request.GET,
        #     'year' in self.request.GET and self.request.GET['year'],
        #     'gearbox' in self.request.GET,
        #     not 'color' in self.request.GET]):
            
        #     output = output.filter(
        #         Q(vendor__in=self.request.GET.getlist('vendor')) &
        #         Q(model__contains=self.request.GET.get('model')) &
        #         Q(year__in=self.request.GET.get('year').split(',')) &
        #         Q(gearbox__in=self.request.GET.getlist('gearbox'))
        #     )



        # else:
        #     if 'vendor' in self.request.GET:
        #         output = output.filter(vendor__in=self.request.GET.getlist('vendor'))
        #     if 'model' in self.request.GET:
        #         output = output.filter(model__contains=self.request.GET.get('model'))
        #     if 'year' in self.request.GET and self.request.GET['year']:                
        #         output = output.filter(year__in=self.request.GET.get('year').split(','))
        #     if 'gearbox' in self.request.GET:
        #         output = output.filter(gearbox__in=self.request.GET.getlist('gearbox'))
        #     if 'color' in self.request.GET:
        #         # нельзя применять ORM для самописных методов модели
        #         # output = output.filter(nearest_color__in=self.request.GET.getlist('color'))
        #         color_filter = [ item.id for item in output \
        #             if item.nearest_color() in self.request.GET.getlist('color')]                
        #         output = output.filter(id__in=color_filter)
        
        # return output

app/templates/app/car_list.html
{% load extratags %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>cars list</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<div class="row mt-5">
			<div class="col-4">
				<h4>Применить фильтр<sup><a href="/">&times;</a></sup></h4>

				<form method="get">
					<div class="form-group">
						<label for="vendorSelect">По производителям:</label>
						<select name="vendor" multiple class="form-control" size="7" id="vendorSelect">                            
							{% for vendor_item in vendor_list %}<option {% if vendor_item in request.GET.vendor %} selected {% endif %}>{{ vendor_item }}</option>{% endfor %}                            
						</select>
					</div>
					<div class="form-group">
						<label for="modelSelect">Модель:</label><br>
						<input class="w-100" type="text" name="model" id="modelSelect" placeholder="Модель или фрагмент названия">
					</div>
					<div class="form-group">
						<label for="gearboxSelect">По типу КПП:</label>
						<select name="gearbox" size=3 multiple class="form-control" id="gearboxSelect">
							<option value="0">механика</option>
							<option value="1">автомат</option>
							<option value="2">робот</option>
						</select>
					</div>
					<div class="form-group">
						<label for="yearSelect">По году производства:</label><br>
						<input type="text" class="w-100" name="year" id="yearSelect" placeholder="Например, 1975, 1961">
					</div>
					<div class="form-group">
					<label>По цвету:</label><br>
						{% for color in colors %}
						<div class="form-check form-check-inline">
							<input class="form-check-input" type="checkbox" id="cb_{{ color.name }}" name="color" value="{{ color.name }}">
							<label class="form-check-label" for="cb_{{ color.name }}">
							<span class="badge" style="background-color: {{ color.web }}; border: 1px solid black">
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span >
							</label>
						</div>
						{% endfor %}
					</div>


					<input type="submit" value="Применить">                    
				
				</form>




			</div>
			<div class="col-8">
				<h2 class="mb-4 text-center">База автомобилей</h2>

				{% if car_list %}
				<table class="table table-sm table-hover text-center">
					<thead class="thead-light">
						<tr>
							<th scope="col">Производитель</th>
							<th scope="col">Модель</th>
							<th scope="col">Год выпуска</th>
							<th scope="col">Тип КПП</th>
							<th scope="col">Цвет</th>
						</tr>
					</thead>
					<tbody>
					{% for car in car_list %}
						<tr>
							<td>{{ car.vendor }}</td>
							<td>{{ car.model }}</td>
							<td>{{ car.year }}</td>
							<td>{{ car.get_gearbox_display }}</td>
							<td><span class="badge" style="background-color: {{ car.color | name_to_web }};" title="{{ car.color }}">&nbsp;&nbsp;&nbsp;</span ></td>
						</tr>
					{% endfor %}
					</tbody>
				</table>

				<nav aria-label="Page navigation example">
				<ul class="pagination justify-content-center">                    
					<li class="page-item"><a class="page-link" href="?{% url_replace page=1 %}">First</a></li>

					{% for page_num in page_list %}
					{% if page_num == page_obj.number %}
					<li class="page-item active">
					{% else %}
					<li class="page-item">
					{% endif %}
					<a class="page-link" href="?{% url_replace page=page_num %}">{{ page_num }}</a></li>
					{% endfor %}

					<li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}">Last</a></li>                    
				</ul>
				</nav>

				{% else %}
				<h3>Поиск не дал результатов либо база автомобилей пуста.</h3>
				{% endif %}            
			</div>
		</div>
	</div>
</body>
</html>